services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: iae-t2-route-schedule
        restart: unless-stopped
        ports:
            # Akses API di http://localhost:8080
            - '${APP_PORT:-8080}:8000'
        environment:
            APP_ENV: local
            APP_DEBUG: 'true'
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: '${DB_DATABASE:-public_transport}'
            DB_USERNAME: '${DB_USERNAME:-sail}'
            DB_PASSWORD: '${DB_PASSWORD:-password}'
            IAE_API_KEY: '${IAE_API_KEY:-102022400143}'
            SERVICE_NAME: '${SERVICE_NAME:-Route-Schedule-Service}'
            API_VERSION: '${API_VERSION:-v1}'
            # Selalu regenerate dokumentasi Swagger supaya URL server selalu benar
            L5_SWAGGER_GENERATE_ALWAYS: 'true'
            L5_SWAGGER_CONST_HOST: 'http://localhost:8080'
        networks:
            - iae
        depends_on:
            mysql:
                condition: service_healthy
    mysql:
        image: 'mysql:8.4'
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-public_transport}'
            MYSQL_USER: '${DB_USERNAME:-sail}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'iae-mysql:/var/lib/mysql'
        networks:
            - iae
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-h'
                - 'localhost'
                - '-p${DB_PASSWORD:-password}'
            retries: 10
            interval: 5s
            timeout: 5s
networks:
    iae:
        driver: bridge
volumes:
    iae-mysql:
        driver: local
