"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-05-23 13:43:32`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

"Indicates what fields are available at the top level of a query operation."
type Query {
    "Find a single user by an identifying attribute."
    user(
      "Search by primary key."
      id: ID @eq @rules(apply: ["prohibits:email", "required_without:email"])

      "Search by email address."
      email: String @eq @rules(apply: ["prohibits:id", "required_without:id", "email"])
    ): User @find

    "List multiple users."
    users(
      "Filters by name. Accepts SQL LIKE wildcards `%` and `_`."
      name: String @where(operator: "like")
    ): [User!]! @paginate(defaultCount: 10)

    "Get all routes."
    routes: [Route!]! @all(model: "App\\Models\\Route")

    "Find a single route by ID."
    route(id: ID! @eq): Route @find(model: "App\\Models\\Route")
}

"Account of a person who uses this application."
type User {
    "Unique primary key."
    id: ID!

    "Non-unique name."
    name: String!

    "Unique email address."
    email: String!

    "When the email was verified."
    email_verified_at: DateTime

    "When the account was created."
    created_at: DateTime!

    "When the account was last updated."
    updated_at: DateTime!
}

"A public transport route."
type Route {
    id: ID!
    route_code: String!
    origin: String!
    destination: String!
    departure_point: String!
    arrival_point: String!
    departure_date: String!
    departure_time: String!
    arrival_time: String!
    vehicle_type: String!
    price: Int!
    seat_capacity: Int!
    available_seats: Int!
    status: String!
    created_at: String
    updated_at: String
}
